dist: xenial
language: node_js
node_js: '12'

repos:
  hackbg/hack-bg-website:
    endpoint: https://api.travis-ci.com/

script:
- yarn build

addons:
  ssh_known_hosts:
    - hack.bg

before_install:
- openssl aes-256-cbc -K $encrypted_92725ca94bf5_key -iv $encrypted_92725ca94bf5_iv
  -in scripts/deploy-key.enc -out scripts/deploy-key -d
- eval "$(ssh-agent -s)"
- cp scripts/deploy-key ~/.ssh/deploy-key
- chmod 600 ~/.ssh/deploy-key
- ssh-add ~/.ssh/deploy-key
- echo -e "Host hack.bg\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

before_deploy: scripts/before-deploy.sh

deploy:
- provider: pages
  skip_cleanup: true
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  local_dir: dist
  repo: "$DEPLOY_REPO"
  target_branch: "$DEPLOY_TARGET_BRANCH"
  name: "$DEPLOY_NAME"
  email: "$DEPLOY_EMAIL"
  on:
    all_branches: true
    condition: "$DEPLOY_REPO"
- provider: script
  skip_cleanup: true
  script: scripts/deploy-stage.sh
  on:
    all_branches: true
